# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm install

    - name: Install PM2
      run: npm install -g pm2
  
    - name: Stop and Delete Existing PM2 Process
      run: pm2 delete index || true  # Prevents failure if process does not exist
  
    - name: Start Application with PM2
      run: pm2 start index.js --name index
  
    - name: Save PM2 Process List
      run: pm2 save
  
    - name: Ensure PM2 Runs on Reboot
      run: pm2 startup

    - name: Pull Latest Code (Optional if needed)
      run: |
        git fetch --all
        git reset --hard origin/main  # Force updates
        git pull origin main

